# This workflow will build and deploy a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17-ea'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn install && mvn clean compile assembly:single
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: aoi-bot
        path: target/aoi-bot-1.0-SNAPSHOT-jar-with-dependencies.jar
        if-no-files-found: error
