# This workflow will build and deploy a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: Build and deploy aoi-bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17-ea'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn install && mvn clean compile assembly:single
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: aoi-bot
        path: target/aoi-bot-1.0-SNAPSHOT-jar-with-dependencies.jar
        if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: aoi-bot
          path: build
      - name: Deploy to server
        run: | 
          echo "Deploying aoi-bot..."
          apt-get install rsync openssh
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          rsync -atv --delete --progress ./build/aoi-bot-1.0-SNAPSHOT-jar-with-dependencies.jar aoi-bot@informatikolympiade.at:/opt/aoi-bot/aoi-bot.jar
          ssh aoi-bot@informatikolympiade.at 'sudo systemctl restart aoi-bot.service'
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
